name: "Run tests"
on:
  push:
    paths:
      - "**.c"
      - "**.cpp"
      - "**.h"
  pull_request:
    paths:
      - "**.c"
      - "**.cpp"
      - "**.h"
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: TheMrMilchmann/setup-msvc-dev@v3
      if: matrix.os == 'windows-latest'
      with:
        arch: x64
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: pip install meson ninja
    - run: meson setup _build
    - run: meson test -C _build -v
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: testlog.txt
        path: _build/meson-logs/testlog.txt
